id: I73638F06
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T08:07:11+00:00'
last_modified: '2022-06-09T18:01:58.902378+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13792
  title: རྡོ་རིང་པཎྜི་ཏ་བསྟན་འཛིན་དཔལ་འབྱོར་ལགས་ཀྱི་སྐུ་ཚེའི་ལོ་རྒྱུས་དང་། གཞས་ཚིག་ཕྱོགས་བསྡུས་དགའ་བའི་གླུ་དབྱངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    7C75:
      image_group_id: I1KG15371
      title: Volume 1 of bod gangs can ljongs kyi gna' bo'i srol rgyun gyi sgyu rtsal
        nang ma dang / stod gzhas gnyis gsar gtod mdzad mkhan rdo ring paN+Di ta bstan
        'dzin dpal 'byor lags kyi sku tshe'i lo rgyus dang / gzhas tshog phyogs bsdus
        dga' ba'i glu dbyangs/
      total_pages: 190
      order: 1
      base_file: 7C75.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
